
services:
  - type: web
    name: unimanager-backend
    env: python
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app.main:app -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: unimanager-db
          property: connectionString
      - key: CLERK_WEBHOOK_SECRET
        sync: false
    autoDeploy: true

databases:
  - name: unimanager-db
    databaseName: unimanager
    user: unimanager
    plan: free
